[tool.black]
line-length = 120
extend-exclude = "alembic"

[tool.isort]
profile = "black"
py_version = 39
skip_gitignore = true
line_length = 120
use_parentheses = true
include_trailing_comma = true
extend_skip = ["alembic"]