"""Create settings table

Revision ID: 441d31311431
Revises: 4c9fceb679b2
Create Date: 2022-04-06 13:09:07.805242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "441d31311431"
down_revision = "4c9fceb679b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "settings",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("title1", sa.Text(), nullable=True),
        sa.Column("title2", sa.Text(), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings")
    # ### end Alembic commands ###
