"""add role column

Revision ID: a9d281f69ad1
Revises: ef8e8e359117
Create Date: 2021-10-18 15:04:41.952473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "a9d281f69ad1"
down_revision = "ef8e8e359117"
branch_labels = None
depends_on = None


def upgrade():
    cart_status = postgresql.ENUM("admin", "uploader", "user", name="role")
    cart_status.create(op.get_bind())

    op.add_column(
        "user", sa.Column("role", sa.Enum(name="role", create_type=False), server_default="admin", nullable=False)
    )
    op.alter_column("user", "role", server_default=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "role")
    # ### end Alembic commands ###
    cart_status = postgresql.ENUM("admin", "uploader", "user", name="role")
    cart_status.drop(op.get_bind())
