"""Add ownership to resources

Revision ID: ddfc4a766e9e
Revises: a9d281f69ad1
Create Date: 2021-10-18 17:48:47.565228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ddfc4a766e9e"
down_revision = "a9d281f69ad1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chapter", sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key("fk_chapter_owner", "chapter", "user", ["owner_id"], ["id"])
    op.add_column("manga", sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key("fk_manga_owner", "manga", "user", ["owner_id"], ["id"])
    op.add_column("uploadsession", sa.Column("fk_session_owner", postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, "uploadsession", "user", ["fk_session_owner"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "uploadsession", type_="foreignkey")
    op.drop_column("uploadsession", "fk_session_owner")
    op.drop_constraint("fk_manga_owner", "manga", type_="foreignkey")
    op.drop_column("manga", "owner_id")
    op.drop_constraint("fk_chapter_owner", "chapter", type_="foreignkey")
    op.drop_column("chapter", "owner_id")
    # ### end Alembic commands ###
